#+options: num:nil toc:nil timestamp:nil title:nil tags:nil
#+BIND: org-export-latex-title-command ""
#+LaTeX_CLASS_OPTIONS: [a4paper,12pt]
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \usepackage{a4wide}
#+SETUPFILE: ~/.emacs.d/org-templates/bibliography.org
#+LaTeX_Header: \renewcommand*{\bibfont}{\footnotesize}


* Working Title
Convexity and Isoperimetry.
* Proposal Summary
** General summary

The classical isoperimetric problem was legendarily solved by Queen Dido of Carthage: if we fix the length of the boundary, which shape has the greatest enclosed area? Her answer: the circle. Similarly, soap bubbles are round because this minimises surface energy. Only recently has the shape of such optimal domains in curved spaces begun to be understood. Recently the applicant and collaborators have made deep contributions to this area using geometric flows, particularly in spaces with variable curvature, where heat equations are used to deform a given domain into an optimal domain. This project will develop these powerful new techniques and apply them to isoperimetric problems in Riemannian manifolds.    

** Public release summary
- Top quality research of international standards.
- Many applications and much to be understood
* Impact Statement
The project aims at conducting top quality mathematical research with internationally renowned mathematicians on deepening the understanding of the geometry of space itself. It will attract collaborators from all around the world, helping to cement Australia's position as an important part of the global mathematics community by answering questions about optimal shapes, giving a geometric picture of energy conservation.
* C1 Career Opportunities
- I obtained a Ph.D. at the Australian National University, Canberra in August 2012.
- I was a visiting researcher at the Beijing International Centre for Mathematics from May 2012 to September 2012, during which time I established numerous connections with leading Chinese mathematicians. China is an emerging research power, and I was very fortunate to have spent time at two of China's most prestigious universities, Peking University and Tsinghua University. It was in Beijing that my understanding of isoperimetric problems began to take shape.
- From July 2012, I have held the prestigious Stephan E. Warschawski Visiting Assistant Professorship at the University of California, San Diego. This is a position awarded to top upcoming mathematicians from all fields. This position does not come with any specific mentor, though I have benefited from experience and advice of Professors Bennett Chow and Lei Ni. I have had the opportunity to participate in several conferences and workshops, establishing connections with top U.S. mathematicians. The University of California, San Diego mathematics department has limited funding however, for hosting seminars and workshops, limiting my access to an active research environment. The position comes with a relatively high teaching load, equivalent to permanent faculty, and greater than that of most post-doctoral positions. As such, my ability to establish a strong research base has been slowed down, but is beginning to bear fruit, with several publications ready for submission with a high potential for several more this year alone. It has been somewhat of a "trial by fire", and a major skill I have learnt is how to balance the numerous demands placed on modern academics, such as teaching, administration and general service to the academic community (e.g. journal refereeing), whilst conducting research.
- In the last 5 years, my research/teaching load, as a fraction of full time load is as follows:

| Year | Research    | Teaching |
|------+-------------+----------|
| 2009 | (Ph.D.) 0.9 |      0.2 |
| 2010 | (Ph.D.) 0.9 |      0.1 |
| 2011 | (Ph.D.) 0.9 |      0.1 |
| 2012 | 0.5         |      0.5 |
| 2013 | 0.4         |      0.6 |

- This project will benefit greatly from access to the internationally renowned Non-linear Analysis and Analysis and Geometry groups at the ANU. In particular, the expertise of members such as Ben Andrews, Neil Trudinger, Andrew Hassell, and Thierry Coulhon is highly relevant to the project. Both groups are very active in research closely aligned with this project, hosting regular seminars and workshops along with regularly hosting international visitors. This active environment, along with a lower teaching load will provide an excellent setting for the execution of this project.
* C2 Research Output					  :exportropeoutputs:
#+BEGIN_LATEX
\doublespacing
#+END_LATEX

** Refereed Journal Articles

1. * *Paul Bryan*. /Isoperimetric Comparison Techniques for Low Dimension Curvature Flows/. Ph.D. Thesis, Australian National University.     
2. * Ben Andrews, *Paul Bryan*. /A comparison theorem for the isoperimetric profile under curve-shortening flow/. Comm. Anal. Geom. 19, 503--539, 2011.
3. * Ben Andrews, *Paul Bryan*. /Curvature bound for curve shortening flow via distance comparison and a direct proof of Grayson's theorem/. J. Reine Angew. Math. 653, 179--187. 2011.
4. * Ben Andrews, *Paul Bryan*. /Curvature bounds by isoperimetric comparison for normalized Ricci flow on the two-sphere/. Calc. Var. Partial Differential Equations 39, 419--428, 2010.

** Other
*** Pre-prints
1. * *Paul Bryan*. /Curvature bounds via an isoperimetric comparison for Ricci flow on surfaces/. 2014. Available http://arxiv.org/abs/1403.4654. 
1. *Paul Bryan*, Janelle Louie. /Ancient solutions of the curve shortening flow on the two-sphere/. 2014.
*** Invited Talks
1. May 2014 /A history of Isoperimetric Problems/. UCSC Colloquium.
2. March 2014 /Isoperimetric Problems in Geometry/. UCI Geometry Seminar.
3. October 2013 /Polar Dual of Convex Bodies and Curvature Flows/. UCSD Differential Geometry Seminar.
4. May 2013 /Isoperimetry and Viscosity Solutions in Geometric Evolution Equations/. Pacific Northwest Geometry Seminar.
5. October 2012 /Isoperimetric comparison techniques for Ricci flow on surfaces/. UCSD Differential Geometry Seminar.
6. Jun 2012 /A Viscosity Equation for the Isoperimetric Profile of Surfaces/. Peking University, Analysis Seminar.
7. Sep 2011 /An Isoperimetric Comparison Theorem for the Ricci Flow on Surfaces/. 55th Annual Australian Mathematical Society Meeting.
8. Aug 2011 /An Isoperimetric Comparison Theorem for the Ricci Flow on Surfaces/. Peking University, Analysis Seminar.
9. Mar 2009 /An Isoperimetric Comparison Theorem for the Ricci Flow on the $2$-sphere/. Workshop on Nonlinear Analysis, Australian National University.
10. Oct 2008 /A Distance Comparison Theorem for the Curve Shortening Flow/. Workshop on Geometric Analysis, University of Wollongong.
11. Feb 2007 /The Curve Shortening Flow: Grayson's Theorem/. AMSI/CSIRO The Big Day In.
* C3 Contributions to the Field			    :exportropecontributions:

I have been working on the connection between isoperimetric problems and curvature flows since my Ph.D. thesis. Using variational techniques, I discovered the underlying structure behind prior investigations \cite{MR1369140,MR1369139,MR1656553} in papers published in either A or A* ranked journals (by the former ARC ranking). This structure manifests itself through a viscosity differential inequality for the /isoperimetric profile/ of a surface and is also described in the pre-print \cite{ricci_iso}. One of the referees for my thesis described the exposition as "one of the clearest explanations of the isoperimetric profile". 

The approach used, for instance in my work with Ben Andrews \cite{MR2729306} extends the isoperimetric comparison techniques in \cite{MR1369140,MR1369139} to obtain a direct curvature bound for solutions of the normalised Ricci flow on the two-sphere, leading directly to a proof that solutions of the normalised Ricci flow smoothly converge to a constant curvature metric. Prior to this, the proof relied on a good deal of extra machinery, beginning with a proof for /positively/ curved metrics in \cite{MR954419} employing a Harnack inequality and then later proven for general metrics in \cite{MR1094458} by employing an entropy inequality. The standout features of our approach are that we were able, via a comparison with a model solution, to obtain the direct curvature bound mentioned above, along with a bound on the isoperimetric constant. The two combined give extremely strong control of the flow, both geometrically and analytically; the latter since the isoperimetric constant equals the Sobolev constant. These results are extended to arbitrary surfaces in \cite{ricci_iso}.

The paper \cite{MR2794630}, was described by the Mathematical Reviews of the AMS as an "...article [that] presents another significant simplifying contribution". We used the viscosity approach to again obtain strong control over the flow in the form of a curvature bound, leading directly to a proof of the Gage-Hamilton-Grayson theorem \cite{MR840401,MR906392} that any embedded curve in the plane smoothly converges to a round circle under the normalised Curve Shortening Flow. The technique was inspired by the distance comparison principle in \cite{MR1656553} which has been generalised to higher dimensions in \cite{MR2967056,MR3011290}. Our paper \cite{MR2794630} strongly influenced the development in higher dimensions, which in turn heavily influenced the recent successes solving the Hsiang-Lawson conjecture \cite{brendlelawson} for minimal tori in $\sphere^3$ and the Pinkall-Stirling conjecture for CMC tori in $\sphere^3$ \cite{2012arXiv1204.5007A}. The paper \cite{alpha_csf_dist_comp} in preparation further elucidates the underlying viscosity equation, and extends it to a greater class of flows.

As further testament to the importance of this approach, in \cite{MR2843240} we offered yet another proof of the Gage-Hamilton-Grayson theorem, obtaining a viscosity equation for the /relative/ isoperimetric profile for the Curve Shortening Flow. 

One striking feature of the comparison results described above, is that the model comparison used comes from an /ancient/ solution of the flow. Ancient solutions are solutions are important in that they model singularity formation of flows, a very active area of current research \cite{MR3020169,MR2993752}. Such solutions have been classified in certain situations in \cite{MR2669361, MR2971286} as either the trivial solutions or the model solutions used in the above comparison results. I have begun exploring the connections in the preprint \cite{csf_ancient_twosphere}, classifying ancient solutions of the Curve Shortening Flow on the two-sphere.

* D2 Organisational Statement				      :exportprojorg:
** Requirements
*** Introduction of Candidate

 - Opportunity to emphasise the suitability of the candidate
*** Alignment

 - Why ANU? – what can ANU offer you (selection criteria: are the necessary facilities available to complete the Project?) and what can you offer ANU
 - Evidence of alignment – link research to a specific theme as outlined in the ANU by 2020 Strategic Plan.
 - Focus on disciplinary and interdisciplinary strengths.
 - Staffing profile – alignment [leadership, management, collaboration, mentoring, supervision].
 - Internal applicants (continuing) – enhance opportunities at ANU e.g. relinquish teaching and administrative commitments and focus on research. If research only position allows capacity building – opportunity for others with the funds that are ‘freed up’ during the Award period. 
 - Internal applicants (fixed term) or External applicants – uniqueness of skills to remain at/brought to ANU. Planned/proposed integration at end of the Award to support continuity of research. Note: this does not need to be via a continuing appointment. The Awardee should be building capacity in a research area strategically aligned to the ANU. How is your research project going to contribute more broadly in this way?

*** Environment

 - Selection criteria: is there an existing, or developing, supportive and highly quality environment for this candidate, their Project and their HDR students?
 - Uniqueness of facilities/environment/staff expertise at ANU as well as uniqueness of your skills/expertise/research area.
 - Highlight the suitability of the research environment for the project itself, not just for the candidate.
 - Highlight collaboration – building research strength across groups/areas/Colleges.

*** Pathways

 - Highlight how the DECRA, by freeing you up from teaching to pursue research, will increase your competitiveness by broadening your profile, as well as your prospects for further employment within the Administering Organisation.
 - Highlight how the DECRA will place you on solid ground to insert your new research into current – or subsequent – teaching programs, thereby building the capacity of undergraduate and graduate students at the Administering Organisation.
 - Expected continuity and/or expansion of research program/s with which your research aligns
 - Relate back to College Strategic Plans, demonstrating that pathways for either research-only and/or research-and-teaching are available to you within the College’s research programs, thereby providing you with a context for your academic career development.
 - Evidence of support structures from senior staff to nurture the candidate’s career directions – training, mentoring etc.
 - Identify training courses and/or programs available to you at the Administering Organisation that will support you to build your research and/or teaching capabilities and skills.
 - Staffing Profile [succession planning, integration, opportunity].

** Response
*** Introduction of Candidate

Paul Bryan is a homegrown researcher, born in Canberra and educated at the ANU, his Ph.D. conferred in August 2012 with thesis completed under the supervision of Prof. Ben Andrews. He then spent several months as a visiting scholar at China's premier institution, Peking University before taking up a three year prestigious SEW Visiting Assistant Professorship at the University of California, San Diego. He then returned briefly to the ANU as a research fellow, followed by the awarding of a highly prized Riemann Fellowship at Leibniz University in Hannover, Germany. Following on, he held a 12 month postdoctoral position at Warwick University in Coventry - one of the UK's strongest modern universities - before returning to Australia for another 12 month postdoctoral position at the University of Queensland  in preparation for permanently remaining in Australia.

 He intends on building a research and teaching career based in Australia and with his wife Kate, raising their children Remy (11 years old) and Lily (7 years old) in Australia. Although extensively travelled and having worked alongside international luminaries in Geometric Analysis such as Peter Topping, Mario Micalef, Bennett Chow, Lei Ni, Gang Tian, Mu-Tao Wang and Knut Smoczyk, not to mention his advisor Ben Andrews, he is a true Australian boy. He very much enjoys the quality of Australian life and is looking forward to the opportunity to strengthen the existing Geometric Analysis culture and reputation in Australia, particularly at the ANU.

 An impressive early research publication record lead to Paul Bryan's appointment in the prestigious SEW Assistant Professor post at UCSD, a position open to applicants from all fields of mathematics. Already having established publications, he focused his energy there on teaching where he taught 6 or 7 classes per year across the entire undergraduate spectrum, whilst running weekly student seminars at both undergraduate and postgraduate level, and supervising an undergraduate research project. He even took on the advisor role (informally as visiting professors are not eligible to formally advice) for Bennett Chow's Ph.D. student Janelle Louise - a highly unusual arrangement for someone in their first academic position. He acted as principal advisor for her final year, guiding her to successfully defending her thesis and publishing joint article in the process.

 Having thus gained significant teaching experience and expertise, after leaving UCSD in late 2015, he refocused his research career, jointly writing four research papers in 2016 all available on the preprint server arXiv and submitted to top journals, the Journal of Differential Geometry, Journal of the European Mathematical Society, Analysis and PDE (accepted) and Communications in Geometry (accepted). With several further papers in preparation, also earmarked for top journals, Paul Bryan is continuing momentum in building a strong research career. These latter accomplishments were balanced by further teaching at Warwick University where he taught entirely a course Advanced Differential Geometry with very favourable student evaluations; such a course is typically (as for example this year) taught by two instructors sharing the load, but the department had such confidence in his abilities they assigned him as sole instructor. Described by Peter Topping as a "true enthusiast [of mathematics]", Paul Bryan has demonstrated excellence in research and teaching, and is primed to build not only a strong individual research career, but to make strong contributions in teaching and the broader research community and is ready to take up leadership roles directing the efforts of students and other early career researchers.

*** Alignment

The Mathematical Sciences Institute (MSI) boasts one of the finest nonlinear analysis groups in the world; it is the ideal host for this project. Researchers with closely related expertise include Prof. Ben Andrews, Prof. Andrew Hassell, Dr. John Urbas, Prof. Neil Trudinger and Prof. Xiu-Jia Wang. Such personnel include recipients of the Australian Mathematical Society Medal, Fellows of the American and Australian Mathematical Societies as well as Fellows of the Royal Society and various other prestiguous awards. The MSI has maintained an excellent standard in mathematics research, complemented by a strong group of postdoctoral researchers and graduate students as well as a highly active visitor program attracting top international mathematicians, including Fields Medalists such as Cedric Vilani and Terrence Tao.

 Historically, the fields of mathematical analysis and in particular, geometric analysis have been a major strength of the MSI. This strength has its roots in the very founding of the Centre for Mathematics in the 1980's, during which time, Neil Trudinger headed the department and pioneers of curvature flows (Gerhard Huisken) as well as analysis and geometric measure theory (Leon Simon) were very active. In more recent times, Ben Andrews has been a shining star, as a focal point for the efforts of geometric analysis across Australia, moving smoothly into a senior role, continuing the tradition of geometric analysis at ANU.

 The mathematical sciences are of the acknowledged strengths of the ANU: in the 2012 ARC Research Excellence report, Pure Mathematics at ANU rated 5 out of 5. The maintenance of these highly research-active disciplines is a key aim of the ANU's strategic plan "ANU by 2020".

 Paul Bryan, as described in the previous section has shown he is a worthy successor to the stellar geometric analysis tradition at the ANU. Recent hiring at the ANU has strengthened other fields, particularly algebra at the ANU, but geometric analysis and non-linear analysis must be maintained to maintain the MSI's international reputation in the field. As such, Paul Bryan is an ideal person to take up the mantle, carrying forward the MSI into the early to mid parts of the new millennium. His early work with Ben Andrews has attracted considerable attention, as is considered by many the the most innovative and direct approach to the curve shortening flow and Ricci flow on surfaces, producing the most lucid proofs of fundamental convergence results. The insights into how focusing on geometric techniques clarifies the analysis - also a feature of Paul Bryan's current research - have been extremely well received in the international research community, with both author's being considered experts in developing such innovative techniques.

*** Environment

The aims of this project complement the existing research of the nonlinear analysis group, but also supplement it, bringing to the fore the deep connections between curvature flows and isoperimetric problems, an area of active international research, but perhaps not yet well represented within the MSI.

 Over the past several years, the MSI has been working to ensure its continued strength and leadership role in the long term, by attracting up-coming researchers. The applied and nonlinear analysis group currently employs no continuing staff aged under 40, with two members already holding fractional pre-retirement positions (Hutchinson, Trudinger). The ANU by 2020 plan stresses long term, strategic research goals, which can only achieved through attracting strong early career researchers to the MSI.

 The addition of Paul Bryan, a promising early career researcher, to the MSI would bolster the MSI's ability to maintain its standing as a top international centre for mathematics research. His research is best described as innovative and illuminating, not only proving strong results, but introducing new techniques to attack difficult problems and clarify deep underlying structure. Such research is vitally important to be undertaken at the ANU in order to maintain it's position as Australia's top research institution, and high standing internationally, particularly as a world-leader in geometric analysis. In particular, Paul Bryan's approach to understand deeper underlying structure is tremendously important in attracting and developing young researchers along with more seasoned researchers, thus creating an internationally renowned centre of expertise.

*** Pathways

Paul Bryan will be given the freedom necessary to pursue his own independent research agenda, with guidance from MSI members as needed. The minimal teaching load will allow him to devote the greater part of his energies towards formulating and executing his research projects. Through such freedom, Paul Bryan will have ample opportunity to demonstrate the ability to instigate and follow through a top-quality research program, enabling him to be competitive in the broader international research community.

 The MSI is a major international centre of mathematical research, and as such attracts many international visitors and has the capacity for hosting world-class conferences and workshops. Therefore, Paul Bryan will have the opportunity to become involved in the organisation and planning of such events, along with inviting distinguished visitors and collaborators to the MSI for the purpose of participating and enhancing research at the MSI. These activities are essential to conducting competitive research and will give Paul Bryan vital skills and experience in these areas. The MSI will allow him the freedom to pursue these endeavours independently, whilst providing support and guidance as needed.

 As a leading Australian university, with the premier mathematics institution in Australia, the MSI attracts the top graduate students in the country as well as many international graduate students. In this environment, Paul Bryan will have the opportunity to take part in supervising graduate and undergraduate research projects, enhancing both his research and teaching experience. This will open many further opportunities for him either at the MSI or at other institutions as his career unfolds. A DECRA at this stage of his career will allow him to fully realise his demonstrated potential to become a leader in the field, both in individual research and in using his network of top mathematicians along with teaching and research supervision excellence to build an internationally renowned research centre in Geometric Analysis at the ANU, attractive to leading researchers and students alike.

* D1 Project Description 				     :exportprojproj:
** Title
Convexity and Isoperimetry with Applications to Geometric Flows.
** Aims and Background

This project has aims falling into one of three broad, related categories: isoperimetry, convexity and geometric flows.

*** _Isoperimetry_

    The isoperimetric profile of a Riemannian manifold was introduced in the 1980's \cite{MR875084,MR999971} to study isoperimetric inequalities on Riemannian manifolds. By definition, for a given real number $x$, the isoperimetric profile $I(x)$ is the infimum of the boundary area of all domains with volume equal to $x$.  For instance, the isoperimetric profile of the plane is $I(x) = \sqrt{4\pi x}$ which follows immediately from the classical isoperimetric inequality $L^2 \geq 4\pi A$. 

  A major outstanding conjecture in this area is the Aubin-Cartan-Hadamard conjecture \cite{MR0448404, MR936419} stating that a Cartan-Hadamard manifold with sectional curvature bounded above by $K_0$ has isoperimetric profile bounded below by the isoperimetric profile of the simply-connected model space of constant section curvature $K_0$. This has been proven in dimension 2 \cite{zbMATH02588223}, dimension 3 \cite{MR1156385,MR2167269} and dimension 4 \cite{MR608287} (for $K_0 = 0$ only), but still remains outstanding in general. Using the curve shortening flow, an analogous comparison for rotationally symmetric model spaces with total positive curvature less than $2\pi$ was obtained in \cite{MR1417620} in dimension $2$. This was also one of the first works to characterise isoperimetric regions in spaces with non-constant curvature. In the twenty or so years since then, much research has been undertaken to increase the understanding of isoperimetric domains \cite{MR1883725, MR1661278} yet in general, as the Aubin-Cartan-Hadamard conjecture suggests, we have only so far scratched the surface of this deep problem.

*Aim 1* _Comparison theorems for the isoperimetric profile._

In \cite{ricci_iso,pbthesis,MR2843240,MR2794630}, a (parabolic) viscosity differential inequality for the isoperimetric profile is used to obtain a comparison principle for the isoperimetric profile evolving under curvature flows. The elliptic version of this inequality is also used to investigate properties of the isoperimetric profile. For example, in positive curvature, the isoperimetric profile is concave and hence isoperimetric regions have connected boundary (see also \cite{MR1674097}).

The aim here is to extend classical comparison results (see e.g. \cite{MR2229062, MR1063226}) under lower curvature bound assumptions for the isoperimetric profile to radial model spaces, such as those studied in \cite{MR839689, MR2836657,MR1417620}. 

*Aim 2* _The isoperimetric profile of covers._ (Collaborator Ben Andrews)
  
In \cite{MR2729306, ricci_iso}, the isoperimetric comparison theorem gives a bound on the isoperimetric constant on the universal cover of a closed surface. It would be desirable to transfer the bound on the isoperimetric constant from the universal cover to the surface, since then very strong control is obtained over the geometry and also the analysis via the Sobolev constant, allowing interpolation techniques to be used to obtain higher regularity. In \cite{MR1354290}, it is shown that the growth of the isoperimetric profile on the universal cover of tori is $\sqrt{Ca}$ with $C\leq 4\pi$ and equality is attained precisely on the flat torus. The aim of this part of the project is to obtain similar control for general surfaces, proving that $I(x)/x^2 \leq C$ with $C \leq (1-\genus)A$, equality being attained on the constant curvature surface.

**** Notes							   :noexport:

  - Maybe I should just try to study certain situations such as radially symmetric or homogeneous/symmetric spaces.
  - The conjecture is probably too much to prove in full generality.
  - It might be possible to prove it for rotationally symmetric manifolds using comparison geometry like in \cite{MR839689}.
  - Levy-Gromov may prove useful, but works on lower curvature bounds.
  - The required inequality is true for geodesic balls. Perhaps one can extend this to convex domains (non-singular Wiengarten map). This connects with the convexity part.
  - Perhaps one can use perturbation arguments, or curvature balls to extend the results from convex domains. Can I compare the second fundamental form (or even just the mean curvature) to the second fundamental form of a curvature ball and hence to the model space?
  - Again connecting with the convexity part, one may be able to perform some kind of symmetrisation in say, symmetric spaces.
  - Extend comparison theorems to manifolds with bounded /total/ curvature via comparison with radial models.
  - Here we want to extend classical comparison results with constant curvature spaces to the radially symmetric case such as in Abresch and later. Since Toponogov works, why not volume comparison?
  - Also, tackling a more general problem than aim 1 may allow for progress in aim 1.

- *Aim 3*:
  
  - Derive the growth of $(n-1)$ dimensional area for Riemannian covering spaces of $n$-dimensional manifolds.
  - Compare Burago-Z- for tori.
  - High genus surfaces would be first.
  - Look at Ben's email with a suggestion about geodesic loops.

**** References							   :noexport:
- Topping iso inequalities \cite{MR1714389}
- Ritore surfaces \cite{MR2167269,MR1883725}
- Morgan, Hass, Hutchings surfaces \cite{MR1417428}\cite{MR1661278}
- Bayle, Rosales: isoprofile \cite{MR2177105,MR2041647}
- Bavard, Pansu \cite{MR875084}
- Sternberg, Zumbrun \cite{MR1674097}
- minimal surfaces \cite{MR764944}
- Aubin-Cartan-Hadamard: Croke, Kleiner, Ritore \cite{MR1156385}, \cite{MR2167269} \cite{MR608287} and references within
- optimal often convex - maximal symmetry constant mean curvature Steiner symmetrisation \cite{MR1849187}
- comparison: particularly profile of smooth domains, \cite{pbthesis}\cite{MR2843240}
- distance comparison: \cite{MR2794630,MR1656553} \cite{MR3011290,MR2967056}
- isoperimetric comparison: \cite{pbthesis,MR2843240,MR2729306,MR1369140,MR1369139}
- isoperimetric inequalities: \cite{MR1849187}, \cite{MR0500557}
- comparison geometry: \cite{MR1063226}
- Heintze: comparison \cite{MR0493885} \cite{MR936318}
- variations and stability: \cite{MR917854,MR731682}

*** _Convexity_

The study of convex bodies has been a source of many rich areas of research over the past couple of centuries, with a rich body of results in Euclidean space, in particular through the work of Aleksandrov, Minkowksi and Brunn \cite{MR1216521}. An important result is the resolution of the Minkowski problem \cite{MR0423267,MR0284956} making strong use of the support function. Convex bodies tend to solve extremum problems such as the isoperimetric problem, as can be seen through Schwarz symmetrisation or spherical symmetrisation as described in \cite{MR1849187, MR2590630} where the height or support function features heavily.

The theory in Euclidean space relies heavily on the linear structure and it is not clear how one would develop a convexity theory in Riemannian manifolds. One approach is to define the support function for the boundary of a smooth convex body with respect to a vector field on the manifold. This approach appears to have been introduced in \cite{MR936318} for simply connected space forms where a satisfactory theory results. Through the work in \cite{MR2002821, MR2114163} it has become apparent that a desirable theory may be obtained for Lie groups with bi-invariant metrics, some quotients thereof, and most generally on manifolds admitting a Killing vector field. In this situation, it has been show that the support function satisfies the very useful Bochner-like formula, closely related to the second variation formula for boundary area linking this part of the project with the isoperimetric part.

*Aim 1* _Convex bodies in Riemannian manifolds._

The aim in this part it is to develop a more general theory of convex bodies in Riemannian manifolds. The principal component is the introduction of a support function for more general Riemannian manifolds than discussed above. 


**** Notes							   :noexport:
**** Refs							   :noexport:

- Support and separation: Schneider \cite{MR1216521}
- Minkowski problem: Yau \cite{MR0423267} \cite{MR0284956}
- Polar dual: theorems? mixed volumes and such.
- Santalo: Hyperbolic space 1944, convex spherical curves \cite{MR0010993} \cite{MR0012456}
- space forms: alencar, frensel \cite{MR1173029}
- support functions:  rifford, fornari, et. al. \cite{MR2114163}

*** _Geometric Flows_

Since the foundational work in \cite{MR664497, MR772132}, curvature flows have become a standard part of the modern geometric analyst's toolkit. The resolution of long standing problems such as the Thurston Geometric Conjecture (and hence the Poincare conjecture as a famous special case) was achieved via the Ricci flow \cite{MR2334563} along with the resolution of long standing sphere theorems \cite{MR2738904, MR2415394} .

*Aim 1* _Isoperimetric comparisons and geometric flows._

The isoperimetric profile and geometric flows are closely related. The mean curvature flow is the gradient flow for the area functional, so one might reasonably expect that solutions will converge to least area hypersurfaces. Under the volume preserving mean curvature flow, uniformly convex hypersurfaces converge to constant mean curvature hypersurfaces \cite{MR921165}. By the first variation formula, these constant mean curvature hypersurfaces include the boundaries of isoperimetric domains. Curvature flows have also been used to prove isoperimetric inequalities \cite{MR726325, MR1417620, MR2420018}. Conversely, isoperimetric inequalities have been used to study singularity formation in curvature flows \cite{MR1650335}. In \cite{ricci_iso,pbthesis,MR2843240,MR2794630}, this sort of connection was exploited to prove convergence results via a comparison theorem for the isoperimetric profile in low dimensions. The aim of this part is to extend these results to higher dimensions.   

*Aim 2* _Convexity and geometric flows._ (Collaborator XuZhong Chen)

Building upon the work in \cite{MR0423267}, and using the support function to parametrise a convex hypersurface, Tso obtained an upper curvature bound, showing that hypersurfaces evolving by the Gauss curvature flow in Euclidean space collapse to points \cite{MR812353}. This approach was extended in \cite{MR1296393} to prove a Harnack inequality for a broad class of curvature flows with numerous applications. In particular, a lower curvature bound may be obtained via the Harnack inequality and a displacement bound \cite{MR1781612} to prove that convex hypersurfaces become round under the flow. An upper curvature bound has been obtained to prove convergence results for flows in Hyperbolic space \cite{curvature_hyperbolic}. The aim of this part of the project is to obtain a Harnack inequality and displacement bound, first in the particular case of hyperbolic space, and then more general manifolds according to the convexity theory developed elsewhere in this project. 

Another fruitful approach to obtain a lower curvature bound has been to consider the evolution of the Polar dual, which satisfies a similar evolution equation as the original hypersurface\cite{MR3078952, 2013arXiv1312.4242I}. This leads to an upper bound for the curvature of the polar dual, and hence by duality to a lower curvature bound for the original hypersurface. This project will aim to apply similar ideas in the context of the convexity theory developed in the project, in particular developing and applying a duality theory in general Riemannian spaces.


**** Notes							   :noexport:
 - Apply isoperimetric comparisons from above to study long-time behaviour and singularity formation in geometric flows.
 - Levy-Gromov and Ricci flow.
 - Ricci flow on Cartan-Hadamard spaces.
 - Maybe radially symmetric, or even asymptotically radially symmetric spaces?
 - What is the connection between isoperimetric model comparisons and Ricci flow?

 - Apply convexity theory to geometric flows in non-Riemannian manifolds to study long-time behaviour and singularity formation in geometric flows (collaborator XuZhong Chen, East China Normal University).
 - Obtain high co-dimension estimates for the support function in the Grassmanian algebra (collaborator Mu-Tao Wang, Columbia University).
 - this would extend Mu-Tao Wang, Mao-Pei Tsui, Knut Smocyzk for graphs.
 - see also Andrews/Baker: curvature pinching?


**** Refs							   :noexport:

- Relation to isoperimetric: Topping, Huisken \cite{MR921165}(volume preserving MCF) \cite{MR1650335} Gage \cite{MR726325}
- Relation to convexity: singularities, self-similarity: Huisken \cite{MR1030675}, White \cite{MR3020169}, Colding-Minicozzi  \cite{MR2993752}
- Ancient solutions and singularities, Daskopolous-Hamilton-Sesum, Rosenau, paper-clip \cite{MR2971286,MR2669361}
- support Tso, Andrews: \cite{MR1296393} \cite{MR812353}
- polar dual flows: Stancu/Ivaki \cite{MR3078952}
- Gerhardt on sphere (2012?)  \cite{2013arXiv1308.1607G}
- Gage-Hamilton-Grayson, Huisken, \cite{MR840401}\cite{MR906392}
- Hamilton \cite{MR954419,MR664497}
- distance comparison: \cite{MR2794630,MR1656553} \cite{MR3011290,MR2967056}
- isoperimetric comparison: \cite{pbthesis,MR2843240,MR2729306,MR1369140,MR1369139}

** Project Quality and Innovation
*** _Isoperimetry_

*Aim 1* _Comparison theorems for the isoperimetric profile._
  
The principal innovation here is to obtain finer comparisons than comparison with constant curvature spaces. This idea was used in \cite{ricci_iso,pbthesis,MR2843240,MR2729306} to extend the isoperimetric comparisons with constant curvature spaces \cite{MR1369140,MR1369139} to radially symmetric comparisons under curvature flows. Here an understanding of the isoperimetric profile of radially symmetric surfaces is required. This has been carried out to a certain extent in \cite{MR1883725} and \cite{MR1714389}. One immediate difficulty encountered is that isoperimetric regions may not be radially symmetric unless curvature conditions are imposed, which may restrict the comparison models allowed, much as in \cite{MR839689, MR2836657}. Alternatively, a comparison with radially symmetric domains may be obtained, even though in general this is not necessarily the isoperimetric profile. This latter technique was already used successfully in \cite{MR2729306}. 

Another aspect of this aim is to obtain comparisons under upper bound curvature assumptions, such as in the Aubin-Cartan-Hadamard conjecture. The comparison is currently known for geodesic balls by classical comparison theorems; an investigation of to what extend this may be extended to (tangentially) convex and star-shaped domains via radial geometry comparison techniques will also be undertaken. This approach is similar to the radial comparison techniques discussed above and will require developing and applying suitable analogues of the Rauch comparison theorem \cite{MR1063226} to the radial geometry setting.

*Aim 2* _The isoperimetric profile of covers._ (Collaborator Ben Andrews)
  
The innovation here is in controlling the length of the shortest geodesic to transfer control of the isoperimetric profile on the universal cover of a closed surface, to that of the closed surface itself. By deforming a closed curve (the boundary of an isoperimetric region on a surface) to a closed geodesic, it is possible to bound the boundary length in terms of the shortest geodesic. This technique uses ideas similar to Blashke's proof of the Gauss-Bonnet theorem \cite{MR0015247}. Already, it looks possible to prove the result for tori (which is already known), and as mentioned the novel part of this approach is for higher genus surfaces. 

**** notes							   :noexport:
 For more general surfaces, an isoperimetric inequality is usually insufficient because of a lack of scaling and since isoperimetric domains (domains with $L = I(A)$) may have varying topological type. For instance on the standard torus, isoperimetric domains are geodesic balls for small $x$ and annuli for larger $x$. The isoperimetric profile encapsulates all this behaviour and thus provides the finer information necessary for the general Riemannian case. Even in the case of surfaces, determining isoperimetric domains is a non-trivial problem; in \cite{MR1883725}, the question of whether isoperimetric domains in rotationally symmetric planes are also rotationally symmetric is addressed. Under the assumption that the Gauss curvature is positive and decreasing in the radial direction, this is proven, however, an example of a rotationally symmetric plane where no isoperimetric domain is rotationally symmetric is also given.

*** _Convexity_

*Aim 1* _Convex bodies in Riemannian manifolds._
 
A major innovation here is through the study is a support function for manifolds with conformal Killing vector fields, in which situation, the Bochner-like formula becomes an inequality. This is still amenable to the maximum principle and similar results as discussed in the backgrounds and aims section above should still be obtainable. This approach has been applied in \cite{MR1722814} to study CMC hypersurfaces in warped product spaces and this looks like just the beginning of the theory. A particular feature of the warped product situation is that the manifold may be foliated by totally geodesic submanifolds, generalising the classical foliation of $\RR^n$ by spheres. A first step in this direction would be to study situations with more rigid geometric structures such as Lie groups and symmetric spaces where suitable foliations may be obtained, and then to move onto the conformal Killing situation. The intermediate steps would be suitable for the involvement of graduate students.

The other major innovation is in determining to what extend these methods may be extended to study even more general situations: the support function may be defined via the vector field $X = d \grad d$, or more generally as a suitably chosen radial vector field $X$. Weak methods and comparison theory must be applied such as in \cite{MR1695025} to obtain regularity of the cut-locus and in \cite{MR2872966, MR2784296} within the context of optimal transport theory. In the latter work, the authors conjecture that the cut-locus is semi-concave, which is proven for surfaces in \cite{MR2784296}. The aim here is to apply such weak methods, and comparison theory to derive results similar to those discussed in the previous paragraph, and to study the question of semi-concavity of the cut-locus. The latter requires second order estimates of the distance function, which will be obtained by applying regularity techniques such as those developed through oscillation estimates for the distance function on a Riemannian manifold \cite{MR2784332}. 

Since the injectivity domain is a star-shaped region in $\RR^n$, there is a natural foliation, and part of this project will involve determining what conditions correspond to suitable foliations (e.g by minimal or constant mean curvature hypersurfaces). Therefore, results obtained here will be applicable to the study of constant mean curvature hypersurfaces and hence also the isoperimetric problem.

*** _Geometric flows_

*Aim 1* _Isoperimetric comparisons and geometric flows._
  
The major contribution of this part of the project will be to determine conditions (topological and/or curvature related) for which the isoperimetric profile satisfies a useful evolution equation under the Ricci flow. The principal difficulty faced here is determining integral curvature invariants such as in the Gauss-Bonnet formula for surfaces. A promising possibility is the K\"ahler-Ricci flow, where there are a number of curvature integral invariants. Appropriate variations will need to be constructed to obtain such curvature invariants, requiring the solutions of second order, non-linear (probably degenerate) equations. Some extra freedom may be obtained from the fact that only inequalities are required and that the addition of tangential components to the second variation formula may be employed without changing the integrals involved. These latter two features should be enough to render the problem tractable, at least in certain symmetric and/or rigid situations such as the K\"ahler case.

*Aim 2* _Convexity and geometric flows._

The innovation in this part is to apply the convexity theory developed in other parts of this project to study curvature flows. In particular, obtaining Harnack inequalities as described in the aims and background section for curvature flows in Riemannian spaces would make available many results obtained for Euclidean space. A theory of polar dual bodies also allows for lower curvature bounds to be obtained as described in the aims and background section.

*** Notes							   :noexport:
The proposed research addresses several current, actively studied problems: the connection between curvature, topology and isoperimetry and obtain more precise comparisons than existing ones. As discussed in "Aims and Background", the understanding of the isoperimetric profile is limited to special cases such as surfaces, constant curvature spaces, and minimal surfaces. The Aubin-Cartan-Hadamard conjecture still remains open despite the relatively simple properties of Cartan-Hadamard manifolds. 

Convexity allows global methods, and the Euclidean case is well understood, but though generalisations are possible, this is still lacking. Many interesting situations are not amenable to such global methods and so some sort of localisation is required.

The connection between these and curvature flows, particularly in singularity formulation is there for the picking. 

My work with flows allows for very strong results to be obtained and is very new and still being explored and understood. It is highly innovative, with no one else realising the connection before. It is also highly effective. The methods should be broadly applicable and the results should be well regarded.

** Research Environment

The MSI is a world renowned centre with a very strong geometric analysis and more generally non-linear analysis group. It is an active group with connections to international universities, and has a long of record of supporting world-class research.

The research environment at the MSI includes leading mathematicians in the field of geometric flows such as Ben Andrews; in the field of non-linear analysis (particularly the calculus of variations) such as Neil Trudinger and Xiu Jia Wang; and in the field of isoperimetry (particularly related to eigenvalue estimates) such as Thierry Colhoun. In the wider research community, Julie Clutterbuck who has very strong results in eigenvalue estimates, and with whom the candidate established a relationship during his time at the ANU, has recently moved from the ANU to Monash. Both she and Ben Andrews have been very supportive in helping the candidate to build a research career, and this is expected to continue throughout the proposed project.

The library and computing facilities at the MSI are first rate, with access to major journals, both in print and online formats. The resources available to the candidate will be at the highest level available at any research institute the world over.

** Feasibility and Benefit
The project builds on the candidates existing expertise and has a high chance of producing strong research outcomes. The aims are ambitious, but involve many intermediate steps along the away, ensuring continual progress throughout the duration of the project. The aims closely align with the expertise of the MSI, with several experts in the field available to offer support and guidance to the candidate.
The research is highly innovative, with strong results already obtained by these methods, and involves international collaboration strengthening Australia's ties with research institutes in the US and China.
The funding requested is minimal, consisting principally of salary and a modest request for travel. Hence the execution of the of the project offers excellent value for money, particularly as the candidates research to date, shows that the methods described in this proposal are extremely effective.
** DECRA Candidate
The MSI will host the candidate during this grant and will make up the shortfall in salary between the DECRA salary and the position at MSI. The teaching and administrative requirements are minimal, allowing the candidate more time to focus on research than has been available to him in the past. At this stage, the candidate will hold no other grants and will have no additional responsibilities besides the teaching and administrative requirements already mentioned. This will allow the candidate to focus his energies on conducting research, allowing him ample time to establish and implement the research program.
** Management of Data
The project will primarily generate research articles, published in scholarly journals, with standard access are re-use arrangements. Preference will be given to open access journals with their access and re-use arrangements.

\printbibliography

** Notes							   :noexport:
*** Convex geometry in Riemannian manifolds
**** support and separation 
- space forms
- Fornari, Rifford
- Tso, Andrews Firey conjecture
- Yau, Minkowski problem
- isoperimetry
- space forms, cartan hadamaard, ritore, morgan, rosales, bayle
- non-smooth methods e.g. viscosity (very popular now)
- networks for non-smooth model problem
- Grassmanian geometry (Mu-Tao Wang, Mao-Pei Tsui)
**** Lie-groups
- Can define a support function
**** Space forms
- Can define a support function
**** General case
- use exponential map and non-smooth techniques like barrier/viscosity
***** semi-localisation (local/global)
- Andrews: non-collapsing
- Localised version of in sphere, out sphere instead of curvature balls?
*** geometric flows
**** singularities
- dumbbell has singularities because of the thin neck compared to the size of the balls. Can one determine this by looking at in/out balls? For convex bodies, there is a good global notion of in/out balls. For non-convex bodies, one should localise, say using curvature balls. Perhaps one can determine the nature of singularities that may form by understanding these curvature balls. For instance, one could compare the ratio of the smallest and largest such balls and if that is not too big, only convex singularities form. Maybe through this approach, one can construct singularity models. The models would have to take into account the topology I suppose, so there would be sphere models, torus models etc.
- Is the Clifford torus a good model for tori comparisons?
* D3 Medical and Dental Research Statement
Not applicable.
* F1-Justification of funding requested from the ARC 	       :exportbudget:
** Year 1
| Item requested           | Cost   | Justification                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|--------------------------+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| *Personnel*              |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| DECRA (Candidate)        | 94 512 | Standard DECRA salary                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                          |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| *Equipment*              |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| Laptop Computer          | 2500   | As part of this proposal, a funding for a laptop computer is requested. This is an essential piece of equipment in an increasingly global and mobile research environment. This proposal includes as an integral part, travel for research visits and participation in international conferences. A laptop computer will allow the participant to continue preparing papers electronically and performing numerical simulations whilst abroad. It is also necessary to remain in touch with local and international collaborators, and students through email, video conferencing, social networking, and other forms of electronic communication. Parts of this proposal involve computational methods to guide the research, whilst the travel requirement imposes the need for long battery life. Thus the requested budget allows for a sufficiently powerful laptop computer with good battery life, a spare battery, and a travel case. The Yoga is chosen since it also is able to function as tablet, allowing note-taking (e.g. at a conference) to be undertaken and also providing facility for annotating presentations in real time. No funding for software is requested as work will be conducted using open source software (e.g. Ubuntu, LaTeX, Python, Sage). |
| (ThinkPad Yoga           |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| Case                     |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| Spare battery)           |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                          |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| *Travel*                 |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| Research visit           | 9 800  | Funding for the cost of one visit per year of three weeks to work with research collaborators is requested. This is an essential part of modern day research and is required as part of this proposal which involves collaboration with international researchers. A sample costing for a visit to Columbia University in New York is provided: Return Airfare: $2500  Accommodation: $200/per night for 20 nights = $4000  Travel allowance: $165/per day for 20 days = $3300 (calculated according to ATO Taxation Determination TD 2013/16)  Total annual cost: $9800                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                          |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| Conference Participation | 5 055  | Participation by the applicant for one international conference per year is requested. Conferences of the calibre of the /International Congress of Mathematicians 2014 (Seoul)/ are envisaged. Such travel will allow the participant to share results with researchers in the field and is absolutely essential to keep up to date with research developments impacting on this proposal. A sample cost for such a conference is provided: Return airfare to Seoul: $2000 Accommodation: $150/night for 7 days = $1050 Travel allowance: $215/day for 7 days = $1505  (calculated according to ATO Taxation Determination TD 2013/16) Total annual cost: $4555                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                          |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                          |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| *Other*                  |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                          |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |

** Year 2
| Item requested           | Cost   | Justification                                                                                                                                                                                                                                                                                                                                                                                                                              |
|--------------------------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| *Personnel*              |        |                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| DECRA (Candidate)        | 94 512 | Standard DECRA salary                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                          |        |                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| *Equipment*              |        |                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                          |        |                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| *Travel*                 |        |                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Research visit           | 9 800  | As in year 1.                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Conference Participation | 5 055  | As in year 1.                                                                                                                                                                                                                                                                                                                                                                                                                              |
|                          |        |                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| *Other*                  |        |                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Open Access Publication  | 900    | This proposal aims to publish papers in open access journals. Many countries are introducing laws requiring government funded research to publicly accessible, and so this project takes the proactive approach of aiming for such publication as a best-practice. Charges for such publications are becoming standard practice. The requested amount of $900 is based on the /Forum of Mathematics/ (Cambridge University Press) charges. |
|                          |        |                                                                                                                                                                                                                                                                                                                                                                                                                                            |

** Year 3

| Item requested           | Cost   | Justification         |
|--------------------------+--------+-----------------------|
| *Personnel*              |        |                       |
| DECRA (Candidate)        | 94 512 | Standard DECRA salary |
|                          |        |                       |
| *Equipment*              |        |                       |
|                          |        |                       |
| *Travel*                 |        |                       |
| Research visit           | 9 800  | As in year 1.         |
| Conference Participation | 5 055  | As in year 1.         |
|                          |        |                       |
| *Other*                  |        |                       |
| Open Access Publication  | 900    | As in year 2.         |
|                          |        |                       |

** Establish Geometric Analysis Forum 				   :noexport:
- Need web hosting for early dissemination and discussion based on SPNET. Leverage existing technology like Google+ for discussions and video conferencing. What about broadcasting seminars from leading geometric analysts?
