* Rejoinder
** Rough Notes
- Reports B and C are very positive.
- Assessor B notes my new papers appear in very strong journals.
- Assessor D wants more elaboration on A and B. Too may different ideas, though B says this is not uncommon. Tie the ideas together better! They all rely on very similar techniques of clever use of geometry and judicious use of the maximum principle. I don't just slog at difficult computations - I find the underlying structures and symmetries, exploiting the geometry to the fullest extent possible.
- Assessor B and D mention the gap in publications and C notes I explain why and picked up speed again. Assessor B notes 4 papers in 2016 which is very strong for this field. Note that I used this time to focus heavily on teaching and supervision and the skills I gained put me in a strong position to provide benefit by teaching and supervising students. Particularly I want to incorporate student research into my program.
- Benefit was not well enough discussed. Mention that I will be able to move into leadership roles. A DECRA will allow me to develop a strong research program. My international and highly respected network will send students and postdocs to Australia. I can establish and maintain Australia's strong position as people Trudinger retire and Andrews moves to more senior roles. Australia's middle career researchers are built today! B notes this project will help a "strong early career researcher build the foundations of an academic career in Australia".
- C says I clearly have a deep understanding, but did not describe sufficiently the methods and major difficulties faced. Say a little about this such as existence of multiple self-similar solutions to network CSF, difficulties in obtain local regularity in time estimates for XCF as noted by Chow/Hamilton. The way to avoid these difficulties is to show stability/instability for network CSF (non symmetric are conjectured to be unstable) and for XCF, the Harnack works very well taking the max principle argument of Chow/Hamilton which is not quite enough, and quantifying it with the Harnack giving sharp precise control. i.e. the max principle just tells you something remains positive, the Harnack quantifies the rate at which it becomes more positive.
- Assessor A says it's not clear if the consequent work is quite as good. I note that the journals are easily as prestigious, and the papers are under serious consideration for acceptance having been with the journals for months if not years (typical acceptance rates of these journals is a year or two) but rejection will usually be much quicker. But also the assessor notes that it's not clear from the proposal - this is primarily because they are recent works whereas the former work has had time to be included e.g. in lecture notes. The work has been presented at conferences in invited talks such as at Warwick and Mission Beach where it was very well received.

** Rejoinder

Assessors (A), (B) and (C) explicitly mention high the quality of the project proposal with assessor (C) using the word "beautiful". Assessor (D) does not state their opinion of the quality either way but expresses concerns about an apparent lack of coherence, which is somewhat echoed by Assessor (B) also. The three projects are all geometric PDE problems and though they differ in precise details, the general methods are to exploit underlying symmetry and geometric structure. Innovative techniques are outlined, building on Dr. Bryan's previous work whereby elegant solutions to problems are obtained by carefully analysing the underlying symmetries and structure rather than by trying to use brute force calculations. All projects rely principally on comparison techniques and insightful use of the maximum principle, exposing deeper beauty and coherence. This aspect of Dr Bryan's work is what has so excited the experts in the field and this is the unifying feature of the three projects.

Assessors (B) and (C) note that the project is very ambitious and may be challenging to complete in the time frame. This is a feature of the project and should be seen as a positive aspect rather than a negative. Australia needs to aim high, funding ambitious projects in order to maintain the stellar reputation it has attained, particularly in the field of Geometric Analysis where the ANU is an internationally recognised leader in the field. The high calibre of Dr. Bryan's research to date, and his international network of world experts, including local world leaders is recognised by the assessors as good evidence that such a project can be completed. This is a strong vote in favour of the project by the assessors who also note the importance of funding such research.

Assessors (B), (D) and (C) mention the gap in publication during the period Dr. Bryan focused on teaching and research supervision while in San Diego. They also mention that after this period, his research output has be excellent giving further evidence that the project can be completed in the time frame. The proposal lays out a solid plan and indicates that much groundwork has already taken place and how early progress is extremely likely. What is needed now is a focused period such as provided by a DECRA, where the details may be developed rigorously bringing the plan to fruition.

Assessor (C) notes Dr. Bryan's deep understanding of the field, but also that the major difficulties are not explicitly stated in the proposal. However, such matters have been taken into account and plans have been developed to address them. For example the network CSF section faces the difficulty that multiple fixed points exist which immediately implies that it is not possible to obtain comparisons for every solution (as opposed to the smooth CSF previously studied by Dr. Bryan). It is conjectured that only the symmetric fixed points are stable, and the comparison techniques described in the paper are able to address this issue, which may then be used to show apart from the non-symmetric fixed points, the comparison holds, simultaneously achieving the goals stated in the proposal and resolving the stability conjecture. Similarly, for the XCF project, in their seminal paper Chow and Hamilton describe that Ben Andrews' expects local regularity in time is needed to complete the program. In that paper, only the maximum principle is employed and this is insufficient. The proposal suggests developing isoperimetric comparisons and the Harnack inequality which yield sharper, quantitative versions of the maximum principle providing the more precise estimates needed.

Assessor (A) states that the proposal does not address whether this work is of the same calibre as the earlier work arising from Dr. Bryan's Ph.D. The main reason for this is that it is new work, and sufficient time has not elapsed for its full impact to be determined. Nevertheless, the calibre may be briefly addressed here. The new papers already have attracted a number of citations (Google Scholar lists over 30 citations in the period 2015-2017) and the work has been well received in invited talks at international conferences such as the 2016-17 Warwick EPSRC Symposium: Geometric PDEs. Moreover, these papers are under consideration (or accepted) by leading journals of equal or better standing to the previous journals. They have been so for sufficiently long periods (6 to 18 months, which is typical for leading mathematical journals) to demonstrate that these journals are seriously considering the papers for publication thus validating their strong calibre.
